name: Build
on:
  push:
  pull_request:

jobs:
  build:
    if: >-
      github.repository_owner != 'pginf-pg-9kisi2023'
      || github.event_name != 'push'
      || github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ github.workflow }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish --no-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: indexer_build_${{ github.sha }}
          path: artifacts/publish/*
          if-no-files-found: error
