name: Publish to GitHub Packages
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Build and pack
        run: dotnet pack -c Release

      - name: Add GitHub Packages as source
        run: |
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push "artifacts\bin\PointProposer\x64\Release\*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source github
