name: Publish to GitHub Packages
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Build
        run: dotnet publish -c Release

      - name: Pack
        run: dotnet pack -c Release --no-build

      - name: Push to NuGet.org
        run: |
          dotnet nuget push "artifacts\bin\PointProposer\x64\Release\*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
